spring.application.name=ms-HistoriaInt

server.port=8084
spring.datasource.url=jdbc:mysql://localhost:3306/db_historiaInt?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=validate