spring.application.name=ms-HistoriaNa

server.port=8085
spring.datasource.url=jdbc:mysql://localhost:3306/db_historiaNa?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=validate