spring.application.name=ms-prestamo

server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/db_prestamos?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=validate