spring.application.name=ms-HistoriaEx

server.port=8086
spring.datasource.url=jdbc:mysql://localhost:3306/db_historiaEx?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=validate